# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.12.7b1.dev111+g5d4eeef'
__version_tuple__ = version_tuple = (0, 12, 7, 'dev111', 'g5d4eeef')
