name: CI

on: 
  - push
  - pull_request
 
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[tests,plotly]
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest --cov h_transport_materials --cov-report xml --cov-report term

    - name: Test import
      run: |
        cd ..
        python -c "import h_transport_materials"

    - name: Upload to codecov
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov

        chmod +x codecov
        ./codecov -t ${{ secrets.CODECOV_TOKEN }}

  check_unused_variables:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose your desired Python version

      - name: Install vulture
        run: pip install vulture

      - name: Check for unused variables
        continue-on-error: true
        run: vulture h_transport_materials/property_database

      - name: Check vulture output
        run: |
          vulture_output=$(vulture h_transport_materials/property_database) || true
          if [[ $vulture_output == *"unused variable"* ]]; then
            echo "Error: Unused variables found."
            exit 1
          fi
